//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FancyWM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FancyWM.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version:.
        /// </summary>
        public static string About_AppVersion {
            get {
                return ResourceManager.GetString("About.AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Caption {
            get {
                return ResourceManager.GetString("About.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2022 Vesko Karaganev. All Rights Reserved..
        /// </summary>
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About.Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string About_Credits {
            get {
                return ResourceManager.GetString("About.Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made possible by the following awesome open-source software..
        /// </summary>
        public static string About_Credits_Description {
            get {
                return ResourceManager.GetString("About.Credits.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced_Caption {
            get {
                return ResourceManager.GetString("Advanced.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create script.
        /// </summary>
        public static string Advanced_Scripting_CreateScript {
            get {
                return ResourceManager.GetString("Advanced.Scripting.CreateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting support is still in preview..
        /// </summary>
        public static string Advanced_Scripting_Description {
            get {
                return ResourceManager.GetString("Advanced.Scripting.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display.
        /// </summary>
        public static string Common_Display {
            get {
                return ResourceManager.GetString("Common.Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved.
        /// </summary>
        public static string Common_Moved {
            get {
                return ResourceManager.GetString("Common.Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string Common_To {
            get {
                return ResourceManager.GetString("Common.To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window.
        /// </summary>
        public static string Common_Window {
            get {
                return ResourceManager.GetString("Common.Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact the developer.
        /// </summary>
        public static string ContactTheDeveloper {
            get {
                return ResourceManager.GetString("ContactTheDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays.
        /// </summary>
        public static string Displays_Caption {
            get {
                return ResourceManager.GetString("Displays.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable tiling on all connected displays.
        /// </summary>
        public static string Displays_MultiMonitorSupport {
            get {
                return ResourceManager.GetString("Displays.MultiMonitorSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart FancyWM for changes to take effect!.
        /// </summary>
        public static string Displays_MultiMonitorSupport_Description {
            get {
                return ResourceManager.GetString("Displays.MultiMonitorSupport.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiling on multiple displays.
        /// </summary>
        public static string Displays_TilingOnMultipleDisplays {
            get {
                return ResourceManager.GetString("Displays.TilingOnMultipleDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error has occurred in FancyWM!.
        /// </summary>
        public static string ErrorMessageBox_Caption {
            get {
                return ResourceManager.GetString("ErrorMessageBox.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyWM will now close. If this issue persists, please check for a solution and/or open a bug report on.
        /// </summary>
        public static string ErrorMessageBox_Description_CheckForSolution {
            get {
                return ResourceManager.GetString("ErrorMessageBox.Description.CheckForSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By submitting a log you can help diagnose the issue. The log file contains a history of the events leading up to the crash. Sensitive information is obfuscated..
        /// </summary>
        public static string ErrorMessageBox_Description_SubmittingALog {
            get {
                return ResourceManager.GetString("ErrorMessageBox.Description.SubmittingALog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart FancyWM.
        /// </summary>
        public static string ErrorMessageBox_RestartFancyWM {
            get {
                return ResourceManager.GetString("ErrorMessageBox.RestartFancyWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit log.
        /// </summary>
        public static string ErrorMessageBox_SubmitLog {
            get {
                return ResourceManager.GetString("ErrorMessageBox.SubmitLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPERIMENTAL.
        /// </summary>
        public static string Experimental {
            get {
                return ResourceManager.GetString("Experimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve empty space in new panels.
        /// </summary>
        public static string General_AllocateNewPanelSpace {
            get {
                return ResourceManager.GetString("General.AllocateNewPanelSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New panels have will have empty space until a second window is added..
        /// </summary>
        public static string General_AllocateNewPanelSpace_Description {
            get {
                return ResourceManager.GetString("General.AllocateNewPanelSpace.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate window movement.
        /// </summary>
        public static string General_AnimateWindowMovement {
            get {
                return ResourceManager.GetString("General.AnimateWindowMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically collapse panels.
        /// </summary>
        public static string General_AutoCollapsePanels {
            get {
                return ResourceManager.GetString("General.AutoCollapsePanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panels with a single window will be removed automatically..
        /// </summary>
        public static string General_AutoCollapsePanels_Description {
            get {
                return ResourceManager.GetString("General.AutoCollapsePanels.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Split Threshold.
        /// </summary>
        public static string General_AutoSplitCount {
            get {
                return ResourceManager.GetString("General.AutoSplitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers automatic panel creation when the focused panel has more than the specified number of children..
        /// </summary>
        public static string General_AutoSplitCount_Description {
            get {
                return ResourceManager.GetString("General.AutoSplitCount.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General_Caption {
            get {
                return ResourceManager.GetString("General.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string General_Interface {
            get {
                return ResourceManager.GetString("General.Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move windows by holding.
        /// </summary>
        public static string General_ModifierMoveWindow {
            get {
                return ResourceManager.GetString("General.ModifierMoveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically activate the moved window.
        /// </summary>
        public static string General_ModifierMoveWindowFocus {
            get {
                return ResourceManager.GetString("General.ModifierMoveWindowFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will activate the window.
        /// </summary>
        public static string General_ModifierMoveWindowFocus_Description {
            get {
                return ResourceManager.GetString("General.ModifierMoveWindowFocus.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show warning on Virtual Desktop Service failure.
        /// </summary>
        public static string General_NotifyVirtualDesktopServiceIncompatibility {
            get {
                return ResourceManager.GetString("General.NotifyVirtualDesktopServiceIncompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyWM tries to use the internal Windows Virtual Desktop Service, which is unsupported by Microsoft. FancyWM can warn you if it is unsupported on this version of Windows..
        /// </summary>
        public static string General_NotifyVirtualDesktopServiceIncompatibility_Description {
            get {
                return ResourceManager.GetString("General.NotifyVirtualDesktopServiceIncompatibility.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override accent color.
        /// </summary>
        public static string General_OverrideAccentColor {
            get {
                return ResourceManager.GetString("General.OverrideAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel font size.
        /// </summary>
        public static string General_PanelFontSize {
            get {
                return ResourceManager.GetString("General.PanelFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel height.
        /// </summary>
        public static string General_PanelHeight {
            get {
                return ResourceManager.GetString("General.PanelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run with administrator privileges.
        /// </summary>
        public static string General_RunsAsAdmin {
            get {
                return ResourceManager.GetString("General.RunsAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyWM is currently running with administrator privileges and can manage all of your windows..
        /// </summary>
        public static string General_RunsAsAdmin_AdminDescription {
            get {
                return ResourceManager.GetString("General.RunsAsAdmin.AdminDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyWM cannot manage windows from elevated processes unless it is run as administrator. Enable this option and restart FancyWM to fix this..
        /// </summary>
        public static string General_RunsAsAdmin_NonAdminDescription {
            get {
                return ResourceManager.GetString("General.RunsAsAdmin.NonAdminDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run automatically at system startup.
        /// </summary>
        public static string General_RunsAtStartup {
            get {
                return ResourceManager.GetString("General.RunsAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show contextual hints in pop-up.
        /// </summary>
        public static string General_ShowContextHints {
            get {
                return ResourceManager.GetString("General.ShowContextHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the list of available keybindings after 1s of inactivity. The command pop-up stays on-screen for longer, but you can close it with.
        /// </summary>
        public static string General_ShowContextHints_Description {
            get {
                return ResourceManager.GetString("General.ShowContextHints.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show focused window reminder.
        /// </summary>
        public static string General_ShowFocusDuringAction {
            get {
                return ResourceManager.GetString("General.ShowFocusDuringAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights the focused window when the command pop-up is shown..
        /// </summary>
        public static string General_ShowFocusDuringAction_Description {
            get {
                return ResourceManager.GetString("General.ShowFocusDuringAction.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show settings.json in containing folder.
        /// </summary>
        public static string General_ShowSettingsConfig {
            get {
                return ResourceManager.GetString("General.ShowSettingsConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the startup window at program startup.
        /// </summary>
        public static string General_ShowStartupWindow {
            get {
                return ResourceManager.GetString("General.ShowStartupWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a sound when an action fails.
        /// </summary>
        public static string General_SoundOnFailure {
            get {
                return ResourceManager.GetString("General.SoundOnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string General_Sounds {
            get {
                return ResourceManager.GetString("General.Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        public static string General_Startup {
            get {
                return ResourceManager.GetString("General.Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiling behavior.
        /// </summary>
        public static string General_TilingBehavior {
            get {
                return ResourceManager.GetString("General.TilingBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window movement.
        /// </summary>
        public static string General_WindowMovement {
            get {
                return ResourceManager.GetString("General.WindowMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window gap.
        /// </summary>
        public static string General_WindowPadding {
            get {
                return ResourceManager.GetString("General.WindowPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help_Caption {
            get {
                return ResourceManager.GetString("Help.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation hotkey.
        /// </summary>
        public static string Keybinding_ActivationHotkey {
            get {
                return ResourceManager.GetString("Keybinding.ActivationHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Keybinding_Cancel_Caption {
            get {
                return ResourceManager.GetString("Keybinding.Cancel.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the action.
        /// </summary>
        public static string Keybinding_Cancel_Description {
            get {
                return ResourceManager.GetString("Keybinding.Cancel.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap in horizontal panel.
        /// </summary>
        public static string Keybinding_CreateHorizontalPanel_Caption {
            get {
                return ResourceManager.GetString("Keybinding.CreateHorizontalPanel.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new horizontal panel around the focused window.
        /// </summary>
        public static string Keybinding_CreateHorizontalPanel_Description {
            get {
                return ResourceManager.GetString("Keybinding.CreateHorizontalPanel.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap in stack panel.
        /// </summary>
        public static string Keybinding_CreateStackPanel_Caption {
            get {
                return ResourceManager.GetString("Keybinding.CreateStackPanel.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new stack panel around the focused window.
        /// </summary>
        public static string Keybinding_CreateStackPanel_Description {
            get {
                return ResourceManager.GetString("Keybinding.CreateStackPanel.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap in vertical panel.
        /// </summary>
        public static string Keybinding_CreateVerticalPanel_Caption {
            get {
                return ResourceManager.GetString("Keybinding.CreateVerticalPanel.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new vertical panel around the focused window.
        /// </summary>
        public static string Keybinding_CreateVerticalPanel_Description {
            get {
                return ResourceManager.GetString("Keybinding.CreateVerticalPanel.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease height.
        /// </summary>
        public static string Keybinding_DecreaseHeight_Caption {
            get {
                return ResourceManager.GetString("Keybinding.DecreaseHeight.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease the height of the focused window.
        /// </summary>
        public static string Keybinding_DecreaseHeight_Description {
            get {
                return ResourceManager.GetString("Keybinding.DecreaseHeight.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease width.
        /// </summary>
        public static string Keybinding_DecreaseWidth_Caption {
            get {
                return ResourceManager.GetString("Keybinding.DecreaseWidth.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease the width of the focused window.
        /// </summary>
        public static string Keybinding_DecreaseWidth_Description {
            get {
                return ResourceManager.GetString("Keybinding.DecreaseWidth.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase height.
        /// </summary>
        public static string Keybinding_IncreaseHeight_Caption {
            get {
                return ResourceManager.GetString("Keybinding.IncreaseHeight.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase the height of the focused window.
        /// </summary>
        public static string Keybinding_IncreaseHeight_Description {
            get {
                return ResourceManager.GetString("Keybinding.IncreaseHeight.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase width.
        /// </summary>
        public static string Keybinding_IncreaseWidth_Caption {
            get {
                return ResourceManager.GetString("Keybinding.IncreaseWidth.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase the width of the focused window.
        /// </summary>
        public static string Keybinding_IncreaseWidth_Description {
            get {
                return ResourceManager.GetString("Keybinding.IncreaseWidth.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string Keybinding_MoveDown_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveDown.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the window next to the window below.
        /// </summary>
        public static string Keybinding_MoveDown_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveDown.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move focus down.
        /// </summary>
        public static string Keybinding_MoveFocusDown_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveFocusDown.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus the window below the current window.
        /// </summary>
        public static string Keybinding_MoveFocusDown_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveFocusDown.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move focus left.
        /// </summary>
        public static string Keybinding_MoveFocusLeft_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveFocusLeft.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus the window to the left of the current window.
        /// </summary>
        public static string Keybinding_MoveFocusLeft_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveFocusLeft.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move focus right.
        /// </summary>
        public static string Keybinding_MoveFocusRight_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveFocusRight.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus the window to the right of the current window.
        /// </summary>
        public static string Keybinding_MoveFocusRight_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveFocusRight.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move focus up.
        /// </summary>
        public static string Keybinding_MoveFocusUp_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveFocusUp.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus the window above the current window.
        /// </summary>
        public static string Keybinding_MoveFocusUp_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveFocusUp.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move left.
        /// </summary>
        public static string Keybinding_MoveLeft_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveLeft.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the window next to the window on the left.
        /// </summary>
        public static string Keybinding_MoveLeft_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveLeft.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move right.
        /// </summary>
        public static string Keybinding_MoveRight_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveRight.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the window next to the window on the right.
        /// </summary>
        public static string Keybinding_MoveRight_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveRight.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to desktop 1.
        /// </summary>
        public static string Keybinding_MoveToDesktop1_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current virtual desktop to virtual desktop 1.
        /// </summary>
        public static string Keybinding_MoveToDesktop1_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop1.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to desktop 2.
        /// </summary>
        public static string Keybinding_MoveToDesktop2_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop2.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current virtual desktop to virtual desktop 2.
        /// </summary>
        public static string Keybinding_MoveToDesktop2_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop2.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to desktop 3.
        /// </summary>
        public static string Keybinding_MoveToDesktop3_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop3.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current virtual desktop to virtual desktop 3.
        /// </summary>
        public static string Keybinding_MoveToDesktop3_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop3.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to desktop 4.
        /// </summary>
        public static string Keybinding_MoveToDesktop4_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop4.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current virtual desktop to virtual desktop 4.
        /// </summary>
        public static string Keybinding_MoveToDesktop4_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop4.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to desktop 5.
        /// </summary>
        public static string Keybinding_MoveToDesktop5_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop5.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current virtual desktop to virtual desktop 5.
        /// </summary>
        public static string Keybinding_MoveToDesktop5_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop5.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to desktop 6.
        /// </summary>
        public static string Keybinding_MoveToDesktop6_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop6.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current virtual desktop to virtual desktop 6.
        /// </summary>
        public static string Keybinding_MoveToDesktop6_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop6.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to desktop 7.
        /// </summary>
        public static string Keybinding_MoveToDesktop7_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop7.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current virtual desktop to virtual desktop 7.
        /// </summary>
        public static string Keybinding_MoveToDesktop7_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop7.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to desktop 8.
        /// </summary>
        public static string Keybinding_MoveToDesktop8_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop8.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current virtual desktop to virtual desktop 8.
        /// </summary>
        public static string Keybinding_MoveToDesktop8_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop8.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to desktop 9.
        /// </summary>
        public static string Keybinding_MoveToDesktop9_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop9.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current virtual desktop to virtual desktop 9.
        /// </summary>
        public static string Keybinding_MoveToDesktop9_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDesktop9.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to display 1.
        /// </summary>
        public static string Keybinding_MoveToDisplay1_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current display to display 1.
        /// </summary>
        public static string Keybinding_MoveToDisplay1_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay1.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to display 2.
        /// </summary>
        public static string Keybinding_MoveToDisplay2_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay2.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current display to display 2.
        /// </summary>
        public static string Keybinding_MoveToDisplay2_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay2.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to display 3.
        /// </summary>
        public static string Keybinding_MoveToDisplay3_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay3.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current display to display 3.
        /// </summary>
        public static string Keybinding_MoveToDisplay3_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay3.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to display 4.
        /// </summary>
        public static string Keybinding_MoveToDisplay4_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay4.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current display to display 4.
        /// </summary>
        public static string Keybinding_MoveToDisplay4_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay4.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to display 5.
        /// </summary>
        public static string Keybinding_MoveToDisplay5_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay5.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current display to display 5.
        /// </summary>
        public static string Keybinding_MoveToDisplay5_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay5.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to display 6.
        /// </summary>
        public static string Keybinding_MoveToDisplay6_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay6.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current display to display 6.
        /// </summary>
        public static string Keybinding_MoveToDisplay6_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay6.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to display 7.
        /// </summary>
        public static string Keybinding_MoveToDisplay7_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay7.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current display to display 7.
        /// </summary>
        public static string Keybinding_MoveToDisplay7_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay7.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to display 8.
        /// </summary>
        public static string Keybinding_MoveToDisplay8_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay8.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current display to display 8.
        /// </summary>
        public static string Keybinding_MoveToDisplay8_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay8.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to display 9.
        /// </summary>
        public static string Keybinding_MoveToDisplay9_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay9.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current display to display 9.
        /// </summary>
        public static string Keybinding_MoveToDisplay9_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToDisplay9.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to previous desktop.
        /// </summary>
        public static string Keybinding_MoveToPreviousDesktop_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToPreviousDesktop.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current virtual desktop to the previous virtual desktop.
        /// </summary>
        public static string Keybinding_MoveToPreviousDesktop_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToPreviousDesktop.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move window to previous display.
        /// </summary>
        public static string Keybinding_MoveToPreviousDisplay_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveToPreviousDisplay.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the focused window from the current display to the previous display.
        /// </summary>
        public static string Keybinding_MoveToPreviousDisplay_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveToPreviousDisplay.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string Keybinding_MoveUp_Caption {
            get {
                return ResourceManager.GetString("Keybinding.MoveUp.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the window next to the window above.
        /// </summary>
        public static string Keybinding_MoveUp_Description {
            get {
                return ResourceManager.GetString("Keybinding.MoveUp.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to upper level.
        /// </summary>
        public static string Keybinding_PullWindowUp_Caption {
            get {
                return ResourceManager.GetString("Keybinding.PullWindowUp.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the window out of its containing panel.
        /// </summary>
        public static string Keybinding_PullWindowUp_Description {
            get {
                return ResourceManager.GetString("Keybinding.PullWindowUp.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force refresh workspace.
        /// </summary>
        public static string Keybinding_RefreshWorkspace_Caption {
            get {
                return ResourceManager.GetString("Keybinding.RefreshWorkspace.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force a change-detection cycle of the whole workspace.
        /// </summary>
        public static string Keybinding_RefreshWorkspace_Description {
            get {
                return ResourceManager.GetString("Keybinding.RefreshWorkspace.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show desktop.
        /// </summary>
        public static string Keybinding_ShowDesktop_Caption {
            get {
                return ResourceManager.GetString("Keybinding.ShowDesktop.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide the desktop.
        /// </summary>
        public static string Keybinding_ShowDesktop_Description {
            get {
                return ResourceManager.GetString("Keybinding.ShowDesktop.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap down.
        /// </summary>
        public static string Keybinding_SwapDown_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwapDown.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap the current window with the window below it.
        /// </summary>
        public static string Keybinding_SwapDown_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwapDown.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap left.
        /// </summary>
        public static string Keybinding_SwapLeft_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwapLeft.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap the current window with the window on its left.
        /// </summary>
        public static string Keybinding_SwapLeft_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwapLeft.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap right.
        /// </summary>
        public static string Keybinding_SwapRight_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwapRight.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap the current window with the window on its right.
        /// </summary>
        public static string Keybinding_SwapRight_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwapRight.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap up.
        /// </summary>
        public static string Keybinding_SwapUp_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwapUp.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap the current window with the window above it.
        /// </summary>
        public static string Keybinding_SwapUp_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwapUp.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to desktop 1.
        /// </summary>
        public static string Keybinding_SwitchToDesktop1_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current virtual desktop to virtual desktop 1.
        /// </summary>
        public static string Keybinding_SwitchToDesktop1_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop1.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to desktop 2.
        /// </summary>
        public static string Keybinding_SwitchToDesktop2_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop2.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current virtual desktop to virtual desktop 2.
        /// </summary>
        public static string Keybinding_SwitchToDesktop2_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop2.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to desktop 3.
        /// </summary>
        public static string Keybinding_SwitchToDesktop3_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop3.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current virtual desktop to virtual desktop 3.
        /// </summary>
        public static string Keybinding_SwitchToDesktop3_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop3.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to desktop 4.
        /// </summary>
        public static string Keybinding_SwitchToDesktop4_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop4.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current virtual desktop to virtual desktop 4.
        /// </summary>
        public static string Keybinding_SwitchToDesktop4_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop4.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to desktop 5.
        /// </summary>
        public static string Keybinding_SwitchToDesktop5_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop5.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current virtual desktop to virtual desktop 5.
        /// </summary>
        public static string Keybinding_SwitchToDesktop5_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop5.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to desktop 6.
        /// </summary>
        public static string Keybinding_SwitchToDesktop6_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop6.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current virtual desktop to virtual desktop 6.
        /// </summary>
        public static string Keybinding_SwitchToDesktop6_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop6.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to desktop 7.
        /// </summary>
        public static string Keybinding_SwitchToDesktop7_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop7.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current virtual desktop to virtual desktop 7.
        /// </summary>
        public static string Keybinding_SwitchToDesktop7_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop7.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to desktop 8.
        /// </summary>
        public static string Keybinding_SwitchToDesktop8_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop8.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current virtual desktop to virtual desktop 8.
        /// </summary>
        public static string Keybinding_SwitchToDesktop8_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop8.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to desktop 9.
        /// </summary>
        public static string Keybinding_SwitchToDesktop9_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop9.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current virtual desktop to virtual desktop 9.
        /// </summary>
        public static string Keybinding_SwitchToDesktop9_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDesktop9.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to display 1.
        /// </summary>
        public static string Keybinding_SwitchToDisplay1_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current display to display 1.
        /// </summary>
        public static string Keybinding_SwitchToDisplay1_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay1.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to display 2.
        /// </summary>
        public static string Keybinding_SwitchToDisplay2_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay2.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current display to display 2.
        /// </summary>
        public static string Keybinding_SwitchToDisplay2_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay2.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to display 3.
        /// </summary>
        public static string Keybinding_SwitchToDisplay3_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay3.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current display to display 3.
        /// </summary>
        public static string Keybinding_SwitchToDisplay3_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay3.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to display 4.
        /// </summary>
        public static string Keybinding_SwitchToDisplay4_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay4.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current display to display 4.
        /// </summary>
        public static string Keybinding_SwitchToDisplay4_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay4.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to display 5.
        /// </summary>
        public static string Keybinding_SwitchToDisplay5_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay5.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current display to display 5.
        /// </summary>
        public static string Keybinding_SwitchToDisplay5_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay5.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to display 6.
        /// </summary>
        public static string Keybinding_SwitchToDisplay6_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay6.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current display to display 6.
        /// </summary>
        public static string Keybinding_SwitchToDisplay6_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay6.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to display 7.
        /// </summary>
        public static string Keybinding_SwitchToDisplay7_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay7.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current display to display 7.
        /// </summary>
        public static string Keybinding_SwitchToDisplay7_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay7.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to display 8.
        /// </summary>
        public static string Keybinding_SwitchToDisplay8_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay8.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current display to display 8.
        /// </summary>
        public static string Keybinding_SwitchToDisplay8_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay8.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to display 9.
        /// </summary>
        public static string Keybinding_SwitchToDisplay9_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay9.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current display to display 9.
        /// </summary>
        public static string Keybinding_SwitchToDisplay9_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToDisplay9.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to previous desktop.
        /// </summary>
        public static string Keybinding_SwitchToPreviousDesktop_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToPreviousDesktop.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current virtual desktop to the previous virtual desktop.
        /// </summary>
        public static string Keybinding_SwitchToPreviousDesktop_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToPreviousDesktop.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to previous display.
        /// </summary>
        public static string Keybinding_SwitchToPreviousDisplay_Caption {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToPreviousDisplay.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch from the current display to the previous display.
        /// </summary>
        public static string Keybinding_SwitchToPreviousDisplay_Description {
            get {
                return ResourceManager.GetString("Keybinding.SwitchToPreviousDisplay.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float window.
        /// </summary>
        public static string Keybinding_ToggleFloatingMode_Caption {
            get {
                return ResourceManager.GetString("Keybinding.ToggleFloatingMode.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle floating mode for the focused window.
        /// </summary>
        public static string Keybinding_ToggleFloatingMode_Description {
            get {
                return ResourceManager.GetString("Keybinding.ToggleFloatingMode.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle window management.
        /// </summary>
        public static string Keybinding_ToggleManager_Caption {
            get {
                return ResourceManager.GetString("Keybinding.ToggleManager.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle FancyWM&apos;s window management functionality.
        /// </summary>
        public static string Keybinding_ToggleManager_Description {
            get {
                return ResourceManager.GetString("Keybinding.ToggleManager.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have to release the key to activate. ⇪ Caps Lock will no longer function normally.
        /// </summary>
        public static string Keybindings_ActivateOnCapsLock_About {
            get {
                return ResourceManager.GetString("Keybindings.ActivateOnCapsLock.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ⇪ Caps Lock as  the Activation hotkey.
        /// </summary>
        public static string Keybindings_ActivateOnCapsLock_Checkbox {
            get {
                return ResourceManager.GetString("Keybindings.ActivateOnCapsLock.Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keybindings.
        /// </summary>
        public static string Keybindings_Caption {
            get {
                return ResourceManager.GetString("Keybindings.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registers the keybinding as a system hotkey, allowing it to be used without the Activation hotkey. The keybinding must use at least one modifier key (Ctrl, Shift, Alt, Win)..
        /// </summary>
        public static string Keybindings_DirectMode_About {
            get {
                return ResourceManager.GetString("Keybindings.DirectMode.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use without Activation hotkey?.
        /// </summary>
        public static string Keybindings_DirectMode_Checkbox {
            get {
                return ResourceManager.GetString("Keybindings.DirectMode.Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows will not allow FancyWM to register a hotkey that is already used by it or another application..
        /// </summary>
        public static string Keybindings_DirectMode_FailModes {
            get {
                return ResourceManager.GetString("Keybindings.DirectMode.FailModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        public static string Keybindings_Focus {
            get {
                return ResourceManager.GetString("Keybindings.Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays.
        /// </summary>
        public static string Keybindings_MultipleDisplays {
            get {
                return ResourceManager.GetString("Keybindings.MultipleDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panels.
        /// </summary>
        public static string Keybindings_Panels {
            get {
                return ResourceManager.GetString("Keybindings.Panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizing.
        /// </summary>
        public static string Keybindings_Sizing {
            get {
                return ResourceManager.GetString("Keybindings.Sizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Desktops.
        /// </summary>
        public static string Keybindings_VirtualDesktops {
            get {
                return ResourceManager.GetString("Keybindings.VirtualDesktops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string Keybindings_Windows {
            get {
                return ResourceManager.GetString("Keybindings.Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are, please take a moment to review it on the Microsoft Store. Thank you for your support!.
        /// </summary>
        public static string Messages_AskForReview {
            get {
                return ResourceManager.GetString("Messages.AskForReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window cannot be resized to fit!.
        /// </summary>
        public static string Messages_CannotBeResizedToFit {
            get {
                return ResourceManager.GetString("Messages.CannotBeResizedToFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not.
        /// </summary>
        public static string Messages_CouldNot {
            get {
                return ResourceManager.GetString("Messages.CouldNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register one or more keybindings as system hotkeys!.
        /// </summary>
        public static string Messages_DirectHotkeyRegistrationFailed {
            get {
                return ResourceManager.GetString("Messages.DirectHotkeyRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying FancyWM?.
        /// </summary>
        public static string Messages_EnjoyingFancyWM {
            get {
                return ResourceManager.GetString("Messages.EnjoyingFancyWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating mode enabled for.
        /// </summary>
        public static string Messages_FloatingModeEnabledFor {
            get {
                return ResourceManager.GetString("Messages.FloatingModeEnabledFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already on.
        /// </summary>
        public static string Messages_IsAlreadyOn {
            get {
                return ResourceManager.GetString("Messages.IsAlreadyOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No focused window!.
        /// </summary>
        public static string Messages_NoFocusedWindow {
            get {
                return ResourceManager.GetString("Messages.NoFocusedWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No previous desktop..
        /// </summary>
        public static string Messages_NoPreviousDesktop {
            get {
                return ResourceManager.GetString("Messages.NoPreviousDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No previous display..
        /// </summary>
        public static string Messages_NoPreviousDisplay {
            get {
                return ResourceManager.GetString("Messages.NoPreviousDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is assigned to.
        /// </summary>
        public static string Messages_NothingIsAssignedTo {
            get {
                return ResourceManager.GetString("Messages.NothingIsAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to do on this desktop..
        /// </summary>
        public static string Messages_NothingToDo {
            get {
                return ResourceManager.GetString("Messages.NothingToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed!.
        /// </summary>
        public static string Messages_OperationFailed {
            get {
                return ResourceManager.GetString("Messages.OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press F12 for help.
        /// </summary>
        public static string Messages_PressF12ForHelp {
            get {
                return ResourceManager.GetString("Messages.PressF12ForHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received invalid command.
        /// </summary>
        public static string Messages_ReceivedInvalidCommand {
            get {
                return ResourceManager.GetString("Messages.ReceivedInvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyWM Error.
        /// </summary>
        public static string Messages_StoreCommunicationFailed_Caption {
            get {
                return ResourceManager.GetString("Messages.StoreCommunicationFailed.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication with the Microsoft Store failed with code.
        /// </summary>
        public static string Messages_StoreCommunicationFailed_Description {
            get {
                return ResourceManager.GetString("Messages.StoreCommunicationFailed.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized keybinding!.
        /// </summary>
        public static string Messages_UnrecognizedKeybinding {
            get {
                return ResourceManager.GetString("Messages.UnrecognizedKeybinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyWM Update Check.
        /// </summary>
        public static string Messages_UpdateCheck_Caption {
            get {
                return ResourceManager.GetString("Messages.UpdateCheck.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of FancyWM is available! Download the latest update in the background?.
        /// </summary>
        public static string Messages_UpdateCheck_UpdateAvailable {
            get {
                return ResourceManager.GetString("Messages.UpdateCheck.UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update download completed! Restart FancyWM to install it?.
        /// </summary>
        public static string Messages_UpdateCheck_UpdateDownloadComplete {
            get {
                return ResourceManager.GetString("Messages.UpdateCheck.UpdateDownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for action....
        /// </summary>
        public static string Messages_WaitingForAction {
            get {
                return ResourceManager.GetString("Messages.WaitingForAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of Windows is not supported!.
        /// </summary>
        public static string Messages_WindowsVersionNotSupported_Caption {
            get {
                return ResourceManager.GetString("Messages.WindowsVersionNotSupported.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyWM tries to use the internal Windows Virtual Desktop Service, which is unsupported by Microsoft. This message can be disabled in Settings.
        ///
        ///It appears that in your version of Windows, Microsoft has changed the VDS interface, and FancyWM cannot detect your virtual desktops.
        ///
        ///If you are running a supported non-Insider Windows build and you see this message, please select Yes to report it..
        /// </summary>
        public static string Messages_WindowsVersionNotSupported_Description {
            get {
                return ResourceManager.GetString("Messages.WindowsVersionNotSupported.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add floating rule for window class.
        /// </summary>
        public static string Overlay_Window_AddRuleForClass {
            get {
                return ResourceManager.GetString("Overlay.Window.AddRuleForClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add floating rule for process.
        /// </summary>
        public static string Overlay_Window_AddRuleForProcess {
            get {
                return ResourceManager.GetString("Overlay.Window.AddRuleForProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag over another window to group.
        /// </summary>
        public static string Overlay_Window_DragActionDetail {
            get {
                return ResourceManager.GetString("Overlay.Window.DragActionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More options.
        /// </summary>
        public static string Overlay_Window_MoreOptions {
            get {
                return ResourceManager.GetString("Overlay.Window.MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click to move to upper level.
        /// </summary>
        public static string Overlay_Window_RightClickToPullUp {
            get {
                return ResourceManager.GetString("Overlay.Window.RightClickToPullUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single click to focus.
        /// </summary>
        public static string Overlay_Window_SingleClickToFocus {
            get {
                return ResourceManager.GetString("Overlay.Window.SingleClickToFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please see.
        /// </summary>
        public static string PleaseSee {
            get {
                return ResourceManager.GetString("PleaseSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Rules_Caption {
            get {
                return ResourceManager.GetString("Rules.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically float by window class.
        /// </summary>
        public static string Rules_ClassIgnoreList {
            get {
                return ResourceManager.GetString("Rules.ClassIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating mode will be automatically enabled for windows with a matching window class. The matching is not case-sensitive and you may use regular expressions..
        /// </summary>
        public static string Rules_ClassIgnoreList_Description {
            get {
                return ResourceManager.GetString("Rules.ClassIgnoreList.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating windows.
        /// </summary>
        public static string Rules_FloatingWindows {
            get {
                return ResourceManager.GetString("Rules.FloatingWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically float by process name.
        /// </summary>
        public static string Rules_ProcessIgnoreList {
            get {
                return ResourceManager.GetString("Rules.ProcessIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating mode will be automatically enabled for windows belonging to one of the processes. Enter one process name per line, excluding the &quot;.exe&quot; extension (e.g. &quot;explorer&quot;). The matching is not case-sensitive and you may use regular expressions..
        /// </summary>
        public static string Rules_ProcessIgnoreList_Description {
            get {
                return ResourceManager.GetString("Rules.ProcessIgnoreList.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyWM Settings.
        /// </summary>
        public static string Settings_FancyWM {
            get {
                return ResourceManager.GetString("Settings.FancyWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyWM Startup.
        /// </summary>
        public static string Startup_Caption {
            get {
                return ResourceManager.GetString("Startup.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyWM is now running!.
        /// </summary>
        public static string Startup_FancyWMIsRunning {
            get {
                return ResourceManager.GetString("Startup.FancyWMIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First-time users:.
        /// </summary>
        public static string Startup_FirstTimeUsers {
            get {
                return ResourceManager.GetString("Startup.FirstTimeUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can always find it in the System Tray..
        /// </summary>
        public static string Startup_InSystemTray {
            get {
                return ResourceManager.GetString("Startup.InSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the layout for the focused window, press the activation keybinding, [⇧ Shift] and [⊞ Win], and once the toast popup is visible, press [H], [V] or [S]..
        /// </summary>
        public static string Startup_Paragraph1 {
            get {
                return ResourceManager.GetString("Startup.Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also hover over the top border of the focused window to change the layout..
        /// </summary>
        public static string Startup_Paragraph2 {
            get {
                return ResourceManager.GetString("Startup.Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this window when FancyWM starts.
        /// </summary>
        public static string Startup_ShowThisWindow {
            get {
                return ResourceManager.GetString("Startup.ShowThisWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot nest panel inside itself!.
        /// </summary>
        public static string TilingError_CausesRecursiveNesting {
            get {
                return ResourceManager.GetString("TilingError.CausesRecursiveNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target panel does not support this operation!.
        /// </summary>
        public static string TilingError_InvalidTarget {
            get {
                return ResourceManager.GetString("TilingError.InvalidTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No adjacent window!.
        /// </summary>
        public static string TilingError_MissingAdjacentWindow {
            get {
                return ResourceManager.GetString("TilingError.MissingAdjacentWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No focused window!.
        /// </summary>
        public static string TilingError_MissingTarget {
            get {
                return ResourceManager.GetString("TilingError.MissingTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify the top-level panel!.
        /// </summary>
        public static string TilingError_ModifiesTopLevelPanel {
            get {
                return ResourceManager.GetString("TilingError.ModifiesTopLevelPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack panel cannot contain other panels!.
        /// </summary>
        public static string TilingError_NestingInStackPanel {
            get {
                return ResourceManager.GetString("TilingError.NestingInStackPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid placement exists!.
        /// </summary>
        public static string TilingError_NoValidPlacementExists {
            get {
                return ResourceManager.GetString("TilingError.NoValidPlacementExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move up any further!.
        /// </summary>
        public static string TilingError_PullsBeyondTopLevelPanel {
            get {
                return ResourceManager.GetString("TilingError.PullsBeyondTopLevelPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot fit in the target panel!.
        /// </summary>
        public static string TilingError_TargetCannotFit {
            get {
                return ResourceManager.GetString("TilingError.TargetCannotFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
