name: .NET Desktop

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    # Install the .NET workload
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Setup Windows SDK
      uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
      with:
        sdk-version: 18362

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        submodules: true

    # Restore the application
    - name: Restore the application
      run: dotnet restore
      env:
        Configuration: ${{ matrix.configuration }}

    # Build the application
    - name: Build the application
      run: dotnet build --no-restore --property WarningLevel=0 FancyWM
      env:
        Configuration: ${{ matrix.configuration }}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    - name: Generate archive
      run: |
        Compress-Archive -Path FancyWM/bin/${{ matrix.configuration }}/net8.0-windows10.0.18362.0/*.* -DestinationPath ${{ matrix.configuration }}.zip
        (Get-FileHash ${{ matrix.configuration }}.zip -Algorithm SHA256).Hash | Out-File ${{ matrix.configuration }}.zip.sha256sum

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ matrix.configuration }}.zip
          ${{ matrix.configuration }}.zip.sha256sum
